INSERT INTO wow_db.guilds(name, server, fraction) VALUES
('Ascent', 'Thrall-US', 'Орда'),
('Afterlife', 'Cenarius-US', 'Альянс'),
('Conquest', 'Kilrogg-US', 'Альянс'),
('Drama', 'Kalesgos-US', 'Альянс'),
('Fury', 'Medivh-US', 'Альянс'),
('Nihilum', 'Magtheridon-EU', 'Орда'),
('Last Resort', 'Kazzak-EU', 'Орда'),
('Method', 'Sylvanas-EU', 'Орда'),
('Death and Taxes', 'Korgath-US', 'Альянс'),
('Ensidia', 'Magtheridon-EU', 'Орда'),
('Vodka', 'Alterac Mountains-US', 'Альянс'),
('Premonition', 'Sen''jin-US', 'Альянс'),
('For the Horde', 'Destromath-EU', 'Орда'),
('Blood Legion', 'Illidan-US', 'Орда'),
('KIN Raiders', 'Blackmoore-KR', 'Альянс'),
('Paragon', 'Lightning''s Blade-EU', 'Орда'),
('Exodus', 'Illidan-US', 'Орда'),
('Ascension', 'Frostmourne-OC', 'Орда'),
('Midwinter', 'Area 52-US', 'Альянс'),
('Limit', 'Illidan-US', 'Орда'),
('SNF', 'Sargeras-US', 'Альянс'),
('Big Dumb Guild', 'Illidan-US', 'Орда'),
('Экзорсус', 'Ревущий фьорд-EU', 'Орда'),
('Echo', 'Tarren Mill-EU', 'Орда'),
('Liquid', 'Illidan-US', 'Орда');